### PR TITLE
info for new maintainer and bumping version

### LINKED ISSUE #4: Use taxize::class2tree somehow
or move here? probably not, but something

### PR DESCRIPTION
**Pull request by LunaSare**
## Description

I added my info to Authors@R field on DESCRIPTION file, and assigned it the "cre" role that signifies for package maintainer. 
I also bumped the version to reflect dev. 

I added a new section to NEWS file to reflect this change.

## Related Issue

Addressing https://github.com/ropensci/brranching/issues/47

## Example

No examples needed for this small change.

### CODE REVIEW

**Comment by LunaSare** [comment]
Hi @maelle! I tried to assign reviewers to my PR, but I do not seem to have permission for that 😅

**Comment by maelle** [comment]
@LunaSare I've now invited you to the GitHub organization and a team with admin access to this repository. As I'm mostly away this week, please ping @ropensci/admin in such questions (there might be delay too but less than waiting for my coming back next week :grin:) Thanks so much for your work on this package and on phylocomr!

**Comment by yabellini** [comment]
@LunaSare do you need any help with this?

**Comment by LunaSare** [comment]
Hi @yabellini, @maelle, and @ropensci/admin, I missed the window to accept your invitation to the organization 😮‍💨 
Would you mind sending it again? Many thanks

**Comment by maelle** [comment]
done

**Pull request merged**
