### PR TITLE
docs: add package vignette #31

### LINKED ISSUE #4: Use taxize::class2tree somehow
or move here? probably not, but something

### PR DESCRIPTION
**Pull request by fozy81**

### CODE REVIEW

**Comment by sckott** [comment]
thanks @fozy81  - A few requests though (I shoudl have put this in the issue, but here it is now):

- please just use `knitr`, so remove `rmarkdown`
- I don't like to have vignettes that render during package build because they can fail when doing web requests and installation takes longer, so please:
    - make an `inst/vign/` folder - and .Rbuildignore this folder
    - put the `.Rmd` vignette in there
    - render the output to `.md`
    - copy the `.md` to `vignettes/` and change the extension to `.Rmd`

thanks!

**Comment by fozy81** [comment]
No problem, I see what you mean. I kinda new there was some convention I wasn't following, thanks for explaining. Will take a look and resubmit update some time soon.

**Comment by sckott** [comment]
thanks

**Comment by fozy81** [comment]
@sckott Sorry not to get back sooner on this, I had some technical issues and other commitments but now back up and running...
I've removed rmarkdown and
   - made an inst/vign/ folder - and .Rbuildignore this folder
   - put the .Rmd vignette in there
   - render the output to .md
    - copy the .md to vignettes/ and change the extension to .Rmd
Let me know if that's looks okay. :smiley:

**Comment by sckott** [comment]
thanks @fozy81 looks good!

**Pull request merged**
